FROM apache/airflow:2.10.5-python3.11

COPY pyproject.toml README.md /opt/project/
COPY src /opt/project/src

USER airflow
RUN pip install --no-cache-dir /opt/project

COPY --chown=airflow:0 dags /opt/airflow/dags
ENV DATA_DIR=/opt/project/data/raw \
    MODEL_DIR=/opt/project/models
